### ISSUE TITLE
Merge #276 broke graphql-helix-defer-stream example

### ISSUE THREAD

**Issue by bugs181** [dotansimha/envelop#809]
**Describe the bug**

It appears merge #276 has broken examples due to context being passed to `getEnveloped()`.

<details>
<summary>Error:</summary>

```bash
$ yarn start
yarn run v1.22.15
warning ../../../../../package.json: No license field
$ ts-node index.ts

/home/levi/Desktop/Projects/graphql-playground/graph-ql-evelop/graphql-helix-defer-stream/node_modules/ts-node/src/index.ts:587
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:151:79 - error TS2554: Expected 0 arguments, but got 1.

151     const { parse, validate, contextFactory, execute, schema } = getEnveloped({ req });
                                                                                  ~~~~~~~

    at createTSError (/home/levi/Desktop/Projects/graphql-playground/graph-ql-evelop/graphql-helix-defer-stream/node_modules/ts-node/src/index.ts:587:12)
    at reportTSError (/home/levi/Desktop/Projects/graphql-playground/graph-ql-evelop/graphql-helix-defer-stream/node_modules/ts-node/src/index.ts:591:19)
    at getOutput (/home/levi/Desktop/Projects/graphql-playground/graph-ql-evelop/graphql-helix-defer-stream/node_modules/ts-node/src/index.ts:921:36)
    at Object.compile (/home/levi/Desktop/Projects/graphql-playground/graph-ql-evelop/graphql-helix-defer-stream/node_modules/ts-node/src/index.ts:1189:32)
    at Module.m._compile (/home/levi/Desktop/Projects/graphql-playground/graph-ql-evelop/graphql-helix-defer-stream/node_modules/ts-node/src/index.ts:1295:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/home/levi/Desktop/Projects/graphql-playground/graph-ql-evelop/graphql-helix-defer-stream/node_modules/ts-node/src/index.ts:1298:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
error Command failed with exit code 1.
```
</details>

<details>
<summary>package.json</summary>

```JSON
{
  "name": "@envelop-examples/graphql-helix-defer-stream",
  "private": true,
  "version": "1.0.0",
  "main": "index.js",
  "author": "Dotan Simha",
  "license": "MIT",
  "dependencies": {
    "fastify": "3.14.0",
    "@envelop/core": "0.2.1",
    "graphql-helix": "1.6.1",
    "@graphql-tools/schema": "8.0.1",
    "graphql": "experimental-stream-defer"
  },
  "devDependencies": {
    "@types/node": "15.6.1",
    "ts-node": "10.0.0",
    "typescript": "4.3.5"
  },
  "scripts": {
    "start": "ts-node index.ts"
  }
}


```
</details>

**To Reproduce**

1. Clone repo
2. Follow directions in [graphql-helix-defer-stream example](https://github.com/dotansimha/envelop/tree/main/examples/graphql-helix-defer-stream) 

**Expected behavior**

Expected not to encounter TS error.

**Environment:**

- OS: `Pop!_OS 20.10`
- `@envelop-core`: `0.2.1`
- NodeJS: `v14.16.0`

**Comment by dotansimha** [comment]
Hi @bugs181 ! Thank you for creating this issue. 
I think you might looking at outdated codebase? The example seems to be updated (https://github.com/dotansimha/envelop/blob/main/examples/graphql-helix-defer-stream/index.ts#L151) , I guess you need to update `@envelop/core` and the plugins? We changed that a few months ago, and the examples are updated to the latest example. (Let me know if it needs to be reopened)

**Comment by bugs181** [comment]
Unfortunately, I just ran this on a completely new development environment and had the same result. You can try the steps for yourself if you'd like.

```bash
$ mkdir graphql-examples && cd graphql-examples
$ git clone https://github.com/dotansimha/envelop
$ cd envelop/examples/graphql-helix-defer-stream
$ yarn install
$ yarn start
```

Error:
```bash
/graphql-examples/envelop/examples/graphql-helix-defer-stream/node_modules/ts-node/src/index.ts:587
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:151:79 - error TS2554: Expected 0 arguments, but got 1.

151     const { parse, validate, contextFactory, execute, schema } = getEnveloped({ req });
    at createTSError (/graphql-examples/envelop/examples/graphql-helix-defer-stream/node_modules/ts-node/src/index.ts:587:12)

```

**Comment by n1ru4l** [comment]
We did not bump the version of `@envelop/core`. This will be fixed by https://github.com/dotansimha/envelop/pull/827
